### PR TITLE
added more items

### PR DESCRIPTION
**Pull request by shameem-dev**

### CODE REVIEW

**Comment by shameem-dev** [comment]
result completed but footer wanted some updates

**Comment by FaleluRahman** [comment]
"use client";

import React, { useState } from "react";

function Campuspoints() {
  const minor = [
    { rank: 1, campus: "Markaz Garden", point: 120 },
    { rank: 2, campus: "Markaz Garden", point: 100 },
    { rank: 3, campus: "Markaz Garden", point: 90 },
    { rank: 4, campus: "Darul Hidaya Campus", point: 80 },
    { rank: "05", campus: "Isra Vatanappally", point: 70 },
    { rank: "06", campus: "Ashabul Badr", point: 50 },
    { rank: "07", campus: "Baithul Izza Narikkuni", point: 40 },
    { rank: "08", campus: "Shuhada Edu", point: 30 },
    { rank: "09", campus: "Markaz Al Munawara", point: 20 },
    { rank: 10, campus: "Markazunnajath", point: 10 },
  ];

  const premeir = [
    { rank: 1, campus: "Imam Rabbani Kanthapuram", point: 140 },
    { rank: 2, campus: "Imam Rabbani Kanthapuram", point: 120 },
    { rank: 3, campus: "Imam Rabbani Kanthapuram", point: 100 },
    { rank: "04", campus: "Darul Hidaya Campus", point: 80 },
    { rank: "05", campus: "Isra Vatanappally", point: 70 },
    { rank: "06", campus: "Ashabul Badr", point: 50 },
    { rank: "07", campus: "Baithul Izza Narikkuni", point: 40 },
    { rank: "08", campus: "Shuhada Edu", point: 30 },
    { rank: "09", campus: "Markaz Al Munawara", point: 20 },
    { rank: 10, campus: "Markazunnajath", point: 10 },
  ];

  const Subjunior = [
    { rank: 1, campus: "Imam Shafi Busthanabad", point: 140 },
    { rank: 2, campus: "Imam Shafi Busthanabad", point: 120 },
    { rank: 3, campus: "Imam Shafi Busthanabad", point: 100 },
    { rank: "4", campus: "Imam Shafi Busthanabad", point: 80 },
    { rank: "05", campus: "Isra Vatanappally", point: 70 },
    { rank: "06", campus: "Ashabul Badr", point: 50 },
    { rank: "07", campus: "Baithul Izza Narikkuni", point: 40 },
    { rank: "08", campus: "Shuhada Edu", point: 30 },
    { rank: "09", campus: "Markaz Al Munawara", point: 20 },
    { rank: 10, campus: "Markazunnajath", point: 10 },
  ];

  const Junior = [
    { rank: 1, campus: "Isra Vatanappally", point: 140 },
    { rank: 2, campus: "Isra Vatanappally", point: 120 },
    { rank: 3, campus: "Isra Vatanappally", point: 100 },
    { rank: "04", campus: "Imam Shafi Busthanabad", point: 80 },
    { rank: "05", campus: "Isra Vatanappally", point: 70 },
    { rank: "06", campus: "Ashabul Badr", point: 50 },
    { rank: "07", campus: "Baithul Izza Narikkuni", point: 40 },
    { rank: "08", campus: "Shuhada Edu", point: 30 },
    { rank: "09", campus: "Markaz Al Munawara", point: 20 },
    { rank: 10, campus: "Markazunnajath", point: 10 },
  ];

  const senior = [
    { rank: 1, campus: "Baithul Izza Narikkuni", point: 140 },
    { rank: 2, campus: "Baithul Izza Narikkuni", point: 120 },
    { rank: 3, campus: "Baithul Izza Narikkuni", point: 100 },
    { rank: "04", campus: "Imam Shafi Busthanabad", point: 80 },
    { rank: "05", campus: "Isra Vatanappally", point: 70 },
    { rank: "06", campus: "Ashabul Badr", point: 50 },
    { rank: "07", campus: "Baithul Izza Narikkuni", point: 40 },
    { rank: "08", campus: "Shuhada Edu", point: 30 },
    { rank: "09", campus: "Markaz Al Munawara", point: 20 },
    { rank: 10, campus: "Markazunnajath", point: 10 },
  ];

  const placeImage: any = {
    1: "/image/1.png",
    2: "/image/2.png",
    3: "/image/3.png",
  };
  const [cat, setCat] = useState("Minor");
  const [view, setView] = useState(false); // State to toggle full data

  return (
    <div className="bg-orange-50 flex flex-col h-fit pt-10 pb-10 ">
      <div className="flex flex-col ml-5 justify-between items-end mr-5">
        {/* <h1 className="bg-red-700  rounded-lg w-fit px-2 font-semibold
 text-white mb-5">Junior</h1> */}
        <div className="grid grid-cols-5 gap-2 w-full">
          {["Minor", "Premeir", "Subjunior", "Junior", "Senior"].map(
            (item: any) => (
              <div
                onClick={() => setCat(item)}
                key={item}
                className={`px-0.5 py-1 rounded-lg text-white text-center
 my-4 ${cat==item ? "bg-red-700 font-bold":" bg-zinc-500 font-sans"}`}
              >
                {item}
              </div>
            )
          )}
        </div>
        {/* {cat} */}
        {/* <div className=" flex w-full justify-end px-1">
        <h1 className="bg-red-700 mt-5 flex rounded-lg w-fit px-2 items-end
font-semibold text-white mb-5">
          After 50
        </h1>
        </div> */}
      </div>
      {/* minor Top 3 Ranks */}
      {cat == "Minor" ? (
        <div className="flex flex-col px-5 gap-1 font-gilroy">
          {minor.slice(0, 3).map((item: any) => (
            <div
              key={item.rank}
              className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
            >
              
              <p className="font-bold">{item.campus}</p>
              <p className="font-bold">{item.point}</p>
            </div>
          ))}

          {/* minor Additional Data */}
          {view &&
            minor.slice(3).map((item: any) => (
              <div
                key={item.rank}
                className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
              >
                <p className="bg-red-800 text-center h-8 w-8 py-1 px-2
text-white rounded-full font-semibold">
                  {item.rank}
                </p>
                <p className="font-medium">{item.campus}</p>
                <p className="font-medium">{item.point}</p>
              </div>
            ))}

          {/* Toggle Button */}
          <button
            className="bg-red-700 rounded-xl text-white font-bold font-sans
py-2 mt-2"
            onClick={() => setView(!view)}
          >
            {!view ? "View More" : "View Less"}
          </button>
        </div>
      ) : cat == "Premeir" ? (
        <div className="flex flex-col px-5 gap-1 font-gilroy">
          {premeir.slice(0, 3).map((item: any) => (
            <div
              key={item.rank}
              className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
            >
              
              <p className="font-bold">{item.campus}</p>
              <p className="font-bold">{item.point}</p>
            </div>
          ))}

          {/* Additional Data */}
          {view &&
            premeir.slice(3).map((item: any) => (
              <div
                key={item.rank}
                className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
              >
                <p className="bg-red-800 py-1 px-2 text-white rounded-full
font-semibold">
                  {item.rank}
                </p>
                <p className="font-medium">{item.campus}</p>
                <p className="font-medium">{item.point}</p>
              </div>
            ))}

          {/* Toggle Button */}
          <button
            className="bg-red-700 rounded-xl text-white font-bold font-sans
py-2 mt-2"
            onClick={() => setView(!view)}
          >
            {!view ? "View More" : "View Less"}
          </button>
        </div>
      ) : cat == "Subjunior" ? (
        <div className="flex flex-col px-5 gap-1 font-gilroy">
          {Subjunior.slice(0, 3).map((item: any) => (
            <div
              key={item.rank}
              className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
            >
              
              <p className="font-bold">{item.campus}</p>
              <p className="font-bold">{item.point}</p>
            </div>
          ))}

          {/* Subjunior Additional Data */}
          {view &&
            Subjunior.slice(3).map((item: any) => (
              <div
                key={item.rank}
                className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
              >
                <p className="bg-red-800 py-1 px-2 text-white rounded-full
font-semibold">
                  {item.rank}
                </p>
                <p className="font-medium">{item.campus}</p>
                <p className="font-medium">{item.point}</p>
              </div>
            ))}

          {/* Toggle Button */}
          <button
            className="bg-red-700 rounded-xl text-white font-bold font-sans
py-2 mt-2"
            onClick={() => setView(!view)}
          >
            {!view ? "View More" : "View Less"}
          </button>
        </div>
      ) : cat == "Junior" ? (
        <div className="flex flex-col px-5 gap-1 font-gilroy">
          {Junior.slice(0, 3).map((item: any) => (
            <div
              key={item.rank}
              className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
            >
              
              <p className="font-bold">{item.campus}</p>
              <p className="font-bold">{item.point}</p>
            </div>
          ))}

          {/* Junior Additional Data */}
          {view &&
            Junior.slice(3).map((item: any) => (
              <div
                key={item.rank}
                className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
              >
                <p className="bg-red-800 py-1 px-2 text-white rounded-full
font-semibold">
                  {item.rank}
                </p>
                <p className="font-medium">{item.campus}</p>
                <p className="font-medium">{item.point}</p>
              </div>
            ))}

          {/* Toggle Button */}
          <button
            className="bg-red-700 rounded-xl text-white font-bold font-sans
py-2 mt-2"
            onClick={() => setView(!view)}
          >
            {!view ? "View More" : "View Less"}
          </button>
        </div>
      ) : (
        cat == "Senior" && (
          <div className="flex flex-col px-5 gap-1 font-gilroy">
            {senior.slice(0, 3).map((item: any) => (
              <div
                key={item.rank}
                className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
              >
                
                <p className="font-bold">{item.campus}</p>
                <p className="font-bold">{item.point}</p>
              </div>
            ))}

            {/* Senior Additional Data */}
            {view &&
              senior.slice(3).map((item: any) => (
                <div
                  key={item.rank}
                  className="p-3 rounded-xl shadow-md bg-white flex
items-center justify-between px-5"
                >
                  <p className="bg-red-800 py-1 px-2 text-white
rounded-full font-semibold">
                    {item.rank}
                  </p>
                  <p className="font-medium">{item.campus}</p>
                  <p className="font-medium">{item.point}</p>
                </div>
              ))}

            {/* Toggle Button */}
          <button
            className="bg-red-700 rounded-xl text-white font-bold font-sans
py-2 mt-2"
            onClick={() => setView(!view)}
          >
            {!view ? "View More" : "View Less"}
          </button>
          </div>
        )
      )}
    </div>
  );
}

export default Campuspoints;

**Comment by shameem-dev** [comment]
"use client";
import React, {useState} from 'react';


const ResultItem = [
    {
        Count: 1,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 2,
        category: 'Junior',
        item: 'Poem Hindi',
        FirstStudentName: 'Ali',
        FirstStudentGroup: 'Alpha TEAM',
        SecondStudentName: 'Rahul',
        SecondStudentGroup: 'Beta TEAM',
        ThirdStudentName: 'Sara',
        ThirdStudentGroup: 'Gamma TEAM',
    },
    {
        Count: 3,
        category: 'Senior',
        item: 'Essay English',
        FirstStudentName: 'John',
        FirstStudentGroup: 'Delta TEAM',
        SecondStudentName: 'Doe',
        SecondStudentGroup: 'Epsilon TEAM',
        ThirdStudentName: 'Anna',
        ThirdStudentGroup: 'Zeta TEAM',
    },
    {
        Count: 4,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 5,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 6,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 7,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 8,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 9,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 10,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 11,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 12,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 13,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 14,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 15,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 16,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 17,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 18,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 19,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 20,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 21,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 22,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 23,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 24,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 25,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 26,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 27,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    },
    {
        Count: 28,
        category: 'Junior',
        item: 'Poem Malayalam',
        FirstStudentName: 'Shame',
        FirstStudentGroup: 'NEW TEAM',
        SecondStudentName: 'Muhammed',
        SecondStudentGroup: 'Second TEAM',
        ThirdStudentName: 'Rasheed',
        ThirdStudentGroup: 'Third TEAM',
    }


];

function ItemResult() {
    const [currentPage, setCurrentPage] = useState<any>(1);
    const [postPerPage, setPostPerPage] = useState(10);

    const lastPostIndex = currentPage * postPerPage;
    const firstPostIndex = lastPostIndex - postPerPage;
    const currentPosts = ResultItem.slice(firstPostIndex, lastPostIndex);



    return (

        <div className="result mt-0 flex flex-wrap-reverse
items-center justify-center w-full gap-5 bg-white p-5 mb-20"
id="result">

            <div className={"p-6 py-3 bg-orange-50 rounded-2xl
shadow-lg flex items-center gap-3"}>
                {currentPage > 1 && <button className={"bg-red-500 p-2
rounded-xl text-white py-2 px-4 font-semibold"}
onClick={()=>setCurrentPage(currentPage>0 &&
currentPage-1)}>Prev</button>
                }
                <p className={'font-semibold'}>{currentPage}</p>

                {(ResultItem.length/postPerPage) > currentPage &&
<button className={"bg-red-500 p-2 rounded-xl text-white py-2 px-4
font-semibold "}
onClick={()=>setCurrentPage(currentPage+1)}>Next</button>
                }  </div>

            {currentPosts.map((item:any,i:number)=>

                <div key={i} className='relative w-[90%] mx-auto
bg-gradient-to-br from-[#ffffff] to-[#fffdee] border
border-[rgba(0,0,0,0.075)] rounded-[14px] p-[20px_30px] box-border
overflow-hidden shadow-[1px_4px_10px_rgba(0,0,0,0.082)]'>


                <h5 className='absolute font-oswald text-[110px]
-top-[55px] font-semibold text-red-200 right-5'>{item.Count}</h5>
                <section id="header"
                         className="header flex items-center
justify-start m-0 border-t border-[#53ffd71a] py-[10px] relative
border-none  bg-transparent h-fit p-0 mb-[15px]">
                    <h6 id="prg-name" className='text-[18px]
text-red-400 m-0 font-medium leading-[15px]'><span
                        className='text-[15px] text-[#696969] m-0
font-normal'>{item.category}</span><br/>{item.item}</h6>
                </section>

                <section
                    className="first flex items-center justify-start
m-0 border-t border-[#53ffd71a] py-[10px] relative">
                    <div className='bg-red-400 h-10 w-10 flex
justify-center items-center text-[#ffffff] rounded-full'>
                        <p className=' m-0 text-shadow-md transform
text-[18px] font-semibold'>1</p>
                    </div>

                    <p id="std-name"
                       className='text-[18px] text-left m-0
text-[rgb(100,100,100)] ml-2 leading-[16px]
shadow-[1px_1px_5px_#ffffff]'>{item.FirstStudentName}<br/><span
                        className='text-[13px] m-0
text-[rgba(0,0,0,0.568)]'>{item.FirstStudentGroup}</span></p>
                </section>
                <section
                    className="first flex items-center justify-start
m-0 border-t border-[#53ffd71a] py-[10px] relative">
                    <div className='bg-red-400 h-10 w-10 flex
justify-center items-center text-[#ffffff] rounded-full'>
                        <p className=' m-0 text-shadow-md transform
text-[18px] font-semibold'>2</p>
                    </div>

                    <p id="std-name"
                       className='text-[18px] text-left m-0
text-[rgb(100,100,100)] ml-2 leading-[16px]
shadow-[1px_1px_5px_#ffffff]'>{item.SecondStudentName}<br/><span
                        className='text-[13px] m-0
text-[rgba(0,0,0,0.568)]'>{item.SecondStudentGroup}</span></p>
                </section>

                <section
                    className="first flex items-center justify-start
m-0 border-t border-[#53ffd71a] py-[10px] relative">
                    <div className='bg-red-400 h-10 w-10 flex
justify-center items-center text-[#ffffff] rounded-full'>
                        <p className='m-0 text-shadow-md transform
text-[18px] font-semibold'>3</p>
                    </div>

                    <p id="std-name"
                       className='text-[18px] text-left m-0
text-[rgb(100,100,100)] ml-2 leading-[16px]
shadow-[1px_1px_5px_#ffffff]'>{item.ThirdStudentName}<br/><span
                        className='text-[13px] m-0
text-[rgba(0,0,0,0.568)]'>{item.ThirdStudentGroup}</span></p>
                </section>

            </div>
                )}




        </div>

    );
}

export default ItemResult;

**Comment by shameem-dev** [comment]
"use client";
import React, { useState, useEffect } from "react";
import Link from "next/link";


const navItems = [
    {
        id: "icon-a",
        label: "Home",
        href: "/",
        left: "15px",
        svg: (
            <svg
                width="50"
                height="50"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="1.5"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
                className="h-[30px] w-[25px] mb-[10px] transition
duration-500 text-black cursor-pointer"
            >
                <path d="M17 21.002H7a4 4 0 0 1-4-4V10.71a4 4 0 0 1
1.927-3.42l5-3.031a4 4 0 0 1 4.146 0l5 3.03A4 4 0 0 1 21 10.71v6.292a4
4 0 0 1-4 4Z" />
                <path d="M9 17h6" />
            </svg>
        ),
    },
    {
        id: "icon-b",
        label: "Results",
        href: "/result",
        left: "87px",
        svg: (
            <svg
                width="46"
                height="46"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="1.5"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
                className="h-[30px] w-[30px] mb-[8px] transition
duration-500 cursor-pointer"
            >
                <path d="M6.745 4h10.568s-.88 13.257-5.284
13.257c-2.151 0-3.461-3.164-4.24-6.4C6.977 7.468 6.746 4 6.746 4Z" />
                <path d="M17.313 4s.922-.982 1.687-1c1.5-.033 1.777 1
1.777 1 .294.61.529 2.195-.88 3.658-1.41 1.463-2.986 2.743-3.628 3.2"
/>
                <path d="M6.745 4S5.785 3.006 5 3c-1.5-.012-1.777
1-1.777 1-.294.61-.529 2.194.88 3.657a29.897 29.897 0 0 0 3.687 3.2"
/>
                <path d="M8.507 20c0-1.828 3.522-2.742
3.522-2.742s3.523.914 3.523 2.743H8.507Z" />
            </svg>
        ),
    },
    {
        id: "icon-c",
        label: "Schedule",
        href: "/gallery",
        left: "158px",
        svg: (

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 25"
                 width="46"
                 height="46"
                 fill="none"

                 strokeLinecap="round"
                 strokeLinejoin="round"
                 strokeWidth="0.9"
                 className="h-[30px] w-[30px] mb-[8px] transition
duration-500 cursor-pointer">
                <defs>
                    <style>{`.cls-1 { fill: #231f20; }`}</style>
                </defs>
                <g id="schedule">
                    <path className="cls-1"
                          d="M22.5 3H21V2a1 1 0 0 0-1-1h-1a1 1 0 0 0-1
1v1h-4V2a1 1 0 0 0-1-1h-1a1 1 0 0 0-1 1v1H7V2a1 1 0 0 0-1-1H5a1 1 0 0
0-1 1v1H2.5A1.5 1.5 0 0 0 1 4.5v18A1.5 1.5 0 0 0 2.5 24h16a5.51 5.51 0
0 0 5.5-5.5v-.13c0-.05 0 0 0 0V4.5A1.5 1.5 0 0 0 22.5 3zM19
2h1v3h-1zm-7 0h1v3h-1zM5 2h1v3H5zM2.5 4H4v1a1 1 0 0 0 1 1h1a1 1 0 0 0
1-1V4h4v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1V4h4v1a1 1 0 0 0 1 1h1a1 1 0 0
0 1-1V4h1.5a.5.5 0 0 1 .5.5V8H2V4.5a.5.5 0 0 1 .5-.5zm16 19a4.5 4.5 0
1 1 4.5-4.5 4.51 4.51 0 0 1-4.5 4.5zm0-10a5.49 5.49 0 0 0-3.15
10H2.5a.5.5 0 0 1-.5-.5V9h21v6.35A5.49 5.49 0 0 0 18.5 13z"/>
                    <path className="cls-1"
                          d="M20.72 19.05 19 18.19V16.5a.5.5 0 0 0-1
0v2a.51.51 0 0 0 .28.45l2 1a.54.54 0 0 0 .22.05.5.5 0 0 0 .22-.95z"/>
                </g>
            </svg>
        ),
    },
    {
        id: "icon-d",
        label: "Schedule",
        href: "/schedule",
        left: "230px",
        svg: (
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 25"
                 fill="none"
                 stroke="currentColor"
                 strokeLinecap="round"
                 strokeLinejoin="round"
                 strokeWidth="0.9"
                 className="h-[30px] w-[30px] mb-[8px] transition
duration-500 cursor-pointer">
                <defs>
                    <style>{`.cls-1 { fill: #231f20; }`}</style>
                </defs>
                <g id="schedule">
                    <path className="cls-1"
                          d="M22.5 3H21V2a1 1 0 0 0-1-1h-1a1 1 0 0 0-1
1v1h-4V2a1 1 0 0 0-1-1h-1a1 1 0 0 0-1 1v1H7V2a1 1 0 0 0-1-1H5a1 1 0 0
0-1 1v1H2.5A1.5 1.5 0 0 0 1 4.5v18A1.5 1.5 0 0 0 2.5 24h16a5.51 5.51 0
0 0 5.5-5.5v-.13c0-.05 0 0 0 0V4.5A1.5 1.5 0 0 0 22.5 3zM19
2h1v3h-1zm-7 0h1v3h-1zM5 2h1v3H5zM2.5 4H4v1a1 1 0 0 0 1 1h1a1 1 0 0 0
1-1V4h4v1a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1V4h4v1a1 1 0 0 0 1 1h1a1 1 0 0
0 1-1V4h1.5a.5.5 0 0 1 .5.5V8H2V4.5a.5.5 0 0 1 .5-.5zm16 19a4.5 4.5 0
1 1 4.5-4.5 4.51 4.51 0 0 1-4.5 4.5zm0-10a5.49 5.49 0 0 0-3.15
10H2.5a.5.5 0 0 1-.5-.5V9h21v6.35A5.49 5.49 0 0 0 18.5 13z"/>
                    <path className="cls-1"
                          d="M20.72 19.05 19 18.19V16.5a.5.5 0 0 0-1
0v2a.51.51 0 0 0 .28.45l2 1a.54.54 0 0 0 .22.05.5.5 0 0 0 .22-.95z"/>
                </g>
            </svg>
        ),
    },
    {
        id: "icon-f",
        label: "Profile",
        href: "/profile",
        left: "300px",
        svg: (
            <svg
                width="46"
                height="46"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="1.5"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
                className="h-[25px] mb-[8px] transition duration-500
cursor-pointer"
            >
                <path d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10
10-4.477 10-10S17.523 2 12 2Z"/>
                <path d="M4.271 18.346s2.23-2.846 7.73-2.846 7.729
2.846 7.729 2.846"/>
                <path d="M12 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
            </svg>
        ),
    },
];

function Navigation() {
    const [activeIcon, setActiveIcon] = useState("");
    const [navLeft, setNavLeft] = useState("");

    useEffect(() => {
        const storedActiveIcon = localStorage.getItem("activeIcon") || "icon-a";
        const storedNavLeft = localStorage.getItem("navLeft") || "15px";
        setActiveIcon(storedActiveIcon);
        setNavLeft(storedNavLeft);
    }, []);

    const handleNavigation = (icon: string, left: string) => {
        setActiveIcon(icon);
        setNavLeft(left);
        localStorage.setItem("activeIcon", icon);
        localStorage.setItem("navLeft", left);
    };

    const getNavClass = (id: string) =>
        `flex flex-col items-center justify-center w-[19%] h-[40px] nav-icon ${
            activeIcon === id ? "act" : ""
        }`;

    return (
        <div
            id="footer"
            className="m-0 mx-auto fixed bottom-0 z-[5]
w-[min(100vw,375px)] flex items-center justify-center
bg-[rgb(221,221,221)] rounded-t-[15px]
shadow-[1px_-3px_10px_rgba(0,0,0,0.116)] h-16 text-black"
        >
            {navItems.map((item) => (
                <nav
                    id={item.id}
                    className={getNavClass(item.id)}
                    onClick={() => handleNavigation(item.id, item.left)}
                    key={item.id}
                    aria-label={item.label}
                >
                    <Link href={item.href}>
                        {item.svg}
                        <p className="text-[10px] mt-[4px] absolute
bottom-[5px] opacity-100 transition duration-500 bg-transparent">
                            {item.label}
                        </p>
                    </Link>
                </nav>
            ))}
            <section
                id="nav-act"
                className="absolute bg-gradient-to-br from-[#db5656]
to-[#e48f8f] shadow-[3px_3px_10px_#bebebe] w-[60px] h-[60px]
rounded-[18px] -z-10 left-[15px] translate-y-[-20px] transition
duration-500"
                style={{ left: navLeft }}
            />
        </div>
    );
}

export default Navigation;

**Pull request merged**
